version: "3"
services:
  mongo:
    image: "mongo"
    ports:
      - '27017:20717'
#  redis:
#    image: 'redis'
#    volumes:
#      - ./data:/data
#    ports:
#      - '6379:6379'
##    expose:
##      - '8001:8001'
##    environment:
##      - ALLOW_EMPTY_PASSWORD=yes
##    networks:
##      - webnet
  zookeeper: # for kafka
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CREATE_TOPICS=test-topic
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  postgresDb: # SQL
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5455:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data5
  pgadmin: # mySQL table- front
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - postgresDb
#volumes:
#  postgresDb:
#    driver: local